CREATE USER test WITH PASSWORD 'postgres';
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE test TO test;

CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;