---
title: "explore_postgres_python"
output: html_document
---

# Python

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

```{python}
import pandas as pd
import psycopg2
import psycopg2.extras as extras
```

```{python}
conn = psycopg2.connect(
  host = "postgres",
  database = "test",
  user = "test",
  password = "postgres"
)
```


```{python}
param_dic = {
    "host"      : "postgres",
    "database"  : "test",
    "user"      : "test",
    "password"  : "postgres"
}
conn = psycopg2.connect(**param_dic)
cur = conn.cursor()
```
```{python}
cur.execute("SELECT * FROM mtcars;")
cur.fetchone()
```

```{python}
def execute_values(conn, df, table):
    """
    Using psycopg2.extras.execute_values() to insert the dataframe
    """
    # Create a list of tupples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL quert to execute
    query  = "INSERT INTO %s(%s) VALUES %%s" % (table, cols)
    cursor = conn.cursor()
    try:
        extras.execute_values(cursor, query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("execute_values() done")
    cursor.close()
```

```{python}

query_create = """
CREATE TABLE iris (
  SepalLength numeric(5,2), 
  SepalWidth numeric(5,2), 
  PetalLength numeric(5,2), 
  PetalWidth numeric(5,2),
  Species char(20)
  );
"""

cur.execute(query_create)
```
```{r}
iris2 <- iris

colnames(iris2) <- c("SepalLength", "SepalWidth", "PetalLength", "PetalWidth", "Species")
iris2
```


```{python}
execute_values(conn = conn, df = r.iris2, table = "iris")
```

```{python}
cur = conn.cursor()
cur.execute("SELECT * FROM iris;")
cur.fetchone()
```

```{python}
pd.read_sql_query('select * from iris',con=conn)
```


